name: Django DevSecOps Pipeline (F1 Free Tier)

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4

      # --- Set up Python ---
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # --- Install dependencies ---
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install bandit safety

      # --- SAST: Bandit ---
      - name: Security scan (Bandit)
        run: bandit -r . --severity-level high

      # --- SCA: Safety ---
      - name: Scan dependencies (safety)
        run: safety scan --full-report  # Changed from 'check' to 'scan'

  deploy-to-azure:
    needs: test-and-scan
    runs-on: ubuntu-latest
    environment: production
    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4

      # --- Azure Login ---
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # --- Verify App Service Exists ---
      - name: Check Azure App Service
        run: |
          az webapp show \
            --name django-azure-app \
            --resource-group django-azure-app_group \
            --query "state" || echo "::warning::App Service not found"

      # --- Deploy to Azure ---
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: "django-azure-app"
          package: .
