name: Django DevSecOps Pipeline (F1 Free Tier)

on:
  push:
    branches: [main]
  pull_request: {}

jobs:
  test-and-scan:
    runs-on: ubuntu-latest
    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4

      

      # --- SAST: Bandit ---
      - name: Security scan (Bandit)
        run: bandit -r . --severity-level high

      # --- SCA: Safety ---
      - name: Check dependencies (safety)
        run: safety check --full-report

     
  deploy-to-azure:
    needs: test-and-scan
    runs-on: ubuntu-latest
    environment: production
    steps:
      # --- Checkout code ---
      - uses: actions/checkout@v4
      
# --- Add Python Setup & Dependency Installation ---
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install gunicorn

      # --- Create Deployment Artifact ---
      - name: Create deployment package
        run: |
          mkdir -p deploy_package
          cp -r . deploy_package/
          cd deploy_package
          echo "python-version=3.10" > runtime.txt
          echo "SCM_DO_BUILD_DURING_DEPLOYMENT=true" > .env

      # --- Azure Login ---
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Fix typo (was AZURE_CREDENTIALS)

    
      # --- Deploy to Azure F1 Tier (No Slots) ---
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: dj  # Must match your F1 App Service name
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: deploy_package  # Deploy the prepared package
          # Removed slot-name (F1 doesn't support slots)
       
          
